//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLY_TA.NYP_svc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NYP_svc.IWsNYP")]
    public interface IWsNYP {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsNYP/GetRegistration", ReplyAction="http://tempuri.org/IWsNYP/GetRegistrationResponse")]
        System.Data.DataSet GetRegistration(int OSEP_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsNYP/GetRegistration", ReplyAction="http://tempuri.org/IWsNYP/GetRegistrationResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetRegistrationAsync(int OSEP_ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsNYPChannel : FLY_TA.NYP_svc.IWsNYP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsNYPClient : System.ServiceModel.ClientBase<FLY_TA.NYP_svc.IWsNYP>, FLY_TA.NYP_svc.IWsNYP {
        
        public WsNYPClient() {
        }
        
        public WsNYPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsNYPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsNYPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsNYPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetRegistration(int OSEP_ID) {
            return base.Channel.GetRegistration(OSEP_ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetRegistrationAsync(int OSEP_ID) {
            return base.Channel.GetRegistrationAsync(OSEP_ID);
        }
    }
}
