//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT2605Prac05_BBS
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderItem
    {
        public int orderItemId { get; set; }
        public int orderId { get; set; }
        public string isbn { get; set; }
        public Nullable<int> orderQty { get; set; }
    
        public virtual order order { get; set; }
    }
}
