//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedStoreWeb.SvcRedStore {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SvcRedStore.IWsSales")]
    public interface IWsSales {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsSales/getAllSales", ReplyAction="http://tempuri.org/IWsSales/getAllSalesResponse")]
        System.Data.DataSet getAllSales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsSales/getAllSales", ReplyAction="http://tempuri.org/IWsSales/getAllSalesResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> getAllSalesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsSales/getSalesByStaff", ReplyAction="http://tempuri.org/IWsSales/getSalesByStaffResponse")]
        System.Data.DataSet getSalesByStaff(string StaffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsSales/getSalesByStaff", ReplyAction="http://tempuri.org/IWsSales/getSalesByStaffResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> getSalesByStaffAsync(string StaffID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsSalesChannel : RedStoreWeb.SvcRedStore.IWsSales, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsSalesClient : System.ServiceModel.ClientBase<RedStoreWeb.SvcRedStore.IWsSales>, RedStoreWeb.SvcRedStore.IWsSales {
        
        public WsSalesClient() {
        }
        
        public WsSalesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsSalesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsSalesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsSalesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet getAllSales() {
            return base.Channel.getAllSales();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getAllSalesAsync() {
            return base.Channel.getAllSalesAsync();
        }
        
        public System.Data.DataSet getSalesByStaff(string StaffID) {
            return base.Channel.getSalesByStaff(StaffID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getSalesByStaffAsync(string StaffID) {
            return base.Channel.getSalesByStaffAsync(StaffID);
        }
    }
}
