//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT2605Prac05_ACME.SvcRefBetterBookSupplier {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/IT2605Prac05_BBS")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ordBookQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ordBookisbnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ordBookQty {
            get {
                return this.ordBookQtyField;
            }
            set {
                if ((this.ordBookQtyField.Equals(value) != true)) {
                    this.ordBookQtyField = value;
                    this.RaisePropertyChanged("ordBookQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ordBookisbn {
            get {
                return this.ordBookisbnField;
            }
            set {
                if ((object.ReferenceEquals(this.ordBookisbnField, value) != true)) {
                    this.ordBookisbnField = value;
                    this.RaisePropertyChanged("ordBookisbn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SvcRefBetterBookSupplier.IWsBookCatalog")]
    public interface IWsBookCatalog {
        
        // CODEGEN: Generating message contract since the wrapper name (MsgContractRequestGetBooks) of message MsgContractRequestGetBooks does not match the default value (GetBooks)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsBookCatalog/GetBooks", ReplyAction="http://tempuri.org/IWsBookCatalog/GetBooksResponse")]
        IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractResponseDataSet GetBooks(IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractRequestGetBooks request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsBookCatalog/GetBooks", ReplyAction="http://tempuri.org/IWsBookCatalog/GetBooksResponse")]
        System.Threading.Tasks.Task<IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractResponseDataSet> GetBooksAsync(IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractRequestGetBooks request);
        
        // CODEGEN: Generating message contract since the wrapper name (MsgContractRequestGetBookDetails) of message MsgContractRequestGetBookDetails does not match the default value (GetBookDetails)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsBookCatalog/GetBookDetails", ReplyAction="http://tempuri.org/IWsBookCatalog/GetBookDetailsResponse")]
        IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractResponseDataSet GetBookDetails(IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractRequestGetBookDetails request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsBookCatalog/GetBookDetails", ReplyAction="http://tempuri.org/IWsBookCatalog/GetBookDetailsResponse")]
        System.Threading.Tasks.Task<IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractResponseDataSet> GetBookDetailsAsync(IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractRequestGetBookDetails request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsBookCatalog/CreateOrders", ReplyAction="http://tempuri.org/IWsBookCatalog/CreateOrdersResponse")]
        int CreateOrders(string customerid, IT2605Prac05_ACME.SvcRefBetterBookSupplier.Order[] bookOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsBookCatalog/CreateOrders", ReplyAction="http://tempuri.org/IWsBookCatalog/CreateOrdersResponse")]
        System.Threading.Tasks.Task<int> CreateOrdersAsync(string customerid, IT2605Prac05_ACME.SvcRefBetterBookSupplier.Order[] bookOrder);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MsgContractRequestGetBooks", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MsgContractRequestGetBooks {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string user;
        
        public MsgContractRequestGetBooks() {
        }
        
        public MsgContractRequestGetBooks(string password, string user) {
            this.password = password;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MsgContractResponseDataSet", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MsgContractResponseDataSet {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet results;
        
        public MsgContractResponseDataSet() {
        }
        
        public MsgContractResponseDataSet(System.Data.DataSet results) {
            this.results = results;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MsgContractRequestGetBookDetails", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MsgContractRequestGetBookDetails {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int bookId;
        
        public MsgContractRequestGetBookDetails() {
        }
        
        public MsgContractRequestGetBookDetails(string password, string user, int bookId) {
            this.password = password;
            this.user = user;
            this.bookId = bookId;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsBookCatalogChannel : IT2605Prac05_ACME.SvcRefBetterBookSupplier.IWsBookCatalog, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsBookCatalogClient : System.ServiceModel.ClientBase<IT2605Prac05_ACME.SvcRefBetterBookSupplier.IWsBookCatalog>, IT2605Prac05_ACME.SvcRefBetterBookSupplier.IWsBookCatalog {
        
        public WsBookCatalogClient() {
        }
        
        public WsBookCatalogClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsBookCatalogClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsBookCatalogClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsBookCatalogClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractResponseDataSet IT2605Prac05_ACME.SvcRefBetterBookSupplier.IWsBookCatalog.GetBooks(IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractRequestGetBooks request) {
            return base.Channel.GetBooks(request);
        }
        
        public System.Data.DataSet GetBooks(string password, string user) {
            IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractRequestGetBooks inValue = new IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractRequestGetBooks();
            inValue.password = password;
            inValue.user = user;
            IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractResponseDataSet retVal = ((IT2605Prac05_ACME.SvcRefBetterBookSupplier.IWsBookCatalog)(this)).GetBooks(inValue);
            return retVal.results;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractResponseDataSet> IT2605Prac05_ACME.SvcRefBetterBookSupplier.IWsBookCatalog.GetBooksAsync(IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractRequestGetBooks request) {
            return base.Channel.GetBooksAsync(request);
        }
        
        public System.Threading.Tasks.Task<IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractResponseDataSet> GetBooksAsync(string password, string user) {
            IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractRequestGetBooks inValue = new IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractRequestGetBooks();
            inValue.password = password;
            inValue.user = user;
            return ((IT2605Prac05_ACME.SvcRefBetterBookSupplier.IWsBookCatalog)(this)).GetBooksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractResponseDataSet IT2605Prac05_ACME.SvcRefBetterBookSupplier.IWsBookCatalog.GetBookDetails(IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractRequestGetBookDetails request) {
            return base.Channel.GetBookDetails(request);
        }
        
        public System.Data.DataSet GetBookDetails(string password, string user, int bookId) {
            IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractRequestGetBookDetails inValue = new IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractRequestGetBookDetails();
            inValue.password = password;
            inValue.user = user;
            inValue.bookId = bookId;
            IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractResponseDataSet retVal = ((IT2605Prac05_ACME.SvcRefBetterBookSupplier.IWsBookCatalog)(this)).GetBookDetails(inValue);
            return retVal.results;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractResponseDataSet> IT2605Prac05_ACME.SvcRefBetterBookSupplier.IWsBookCatalog.GetBookDetailsAsync(IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractRequestGetBookDetails request) {
            return base.Channel.GetBookDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractResponseDataSet> GetBookDetailsAsync(string password, string user, int bookId) {
            IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractRequestGetBookDetails inValue = new IT2605Prac05_ACME.SvcRefBetterBookSupplier.MsgContractRequestGetBookDetails();
            inValue.password = password;
            inValue.user = user;
            inValue.bookId = bookId;
            return ((IT2605Prac05_ACME.SvcRefBetterBookSupplier.IWsBookCatalog)(this)).GetBookDetailsAsync(inValue);
        }
        
        public int CreateOrders(string customerid, IT2605Prac05_ACME.SvcRefBetterBookSupplier.Order[] bookOrder) {
            return base.Channel.CreateOrders(customerid, bookOrder);
        }
        
        public System.Threading.Tasks.Task<int> CreateOrdersAsync(string customerid, IT2605Prac05_ACME.SvcRefBetterBookSupplier.Order[] bookOrder) {
            return base.Channel.CreateOrdersAsync(customerid, bookOrder);
        }
    }
}
