//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT2605Prac05_ACME.SvcRefBetterBookSupplier {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SvcRefBetterBookSupplier.IWsBookCatalog")]
    public interface IWsBookCatalog {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsBookCatalog/GetBooks", ReplyAction="http://tempuri.org/IWsBookCatalog/GetBooksResponse")]
        System.Data.DataSet GetBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsBookCatalog/GetBooks", ReplyAction="http://tempuri.org/IWsBookCatalog/GetBooksResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsBookCatalog/GetBookDetails", ReplyAction="http://tempuri.org/IWsBookCatalog/GetBookDetailsResponse")]
        System.Data.DataSet GetBookDetails(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsBookCatalog/GetBookDetails", ReplyAction="http://tempuri.org/IWsBookCatalog/GetBookDetailsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetBookDetailsAsync(int bookId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsBookCatalogChannel : IT2605Prac05_ACME.SvcRefBetterBookSupplier.IWsBookCatalog, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsBookCatalogClient : System.ServiceModel.ClientBase<IT2605Prac05_ACME.SvcRefBetterBookSupplier.IWsBookCatalog>, IT2605Prac05_ACME.SvcRefBetterBookSupplier.IWsBookCatalog {
        
        public WsBookCatalogClient() {
        }
        
        public WsBookCatalogClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsBookCatalogClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsBookCatalogClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsBookCatalogClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetBooks() {
            return base.Channel.GetBooks();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetBooksAsync() {
            return base.Channel.GetBooksAsync();
        }
        
        public System.Data.DataSet GetBookDetails(int bookId) {
            return base.Channel.GetBookDetails(bookId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetBookDetailsAsync(int bookId) {
            return base.Channel.GetBookDetailsAsync(bookId);
        }
    }
}
