//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCHealth.bbs_svc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/IT2605Prac05_BBS.DAL")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ordBookQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ordBookisbnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ordBookQty {
            get {
                return this.ordBookQtyField;
            }
            set {
                if ((this.ordBookQtyField.Equals(value) != true)) {
                    this.ordBookQtyField = value;
                    this.RaisePropertyChanged("ordBookQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ordBookisbn {
            get {
                return this.ordBookisbnField;
            }
            set {
                if ((object.ReferenceEquals(this.ordBookisbnField, value) != true)) {
                    this.ordBookisbnField = value;
                    this.RaisePropertyChanged("ordBookisbn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="bbs_svc.IWsBookCatalog")]
    public interface IWsBookCatalog {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsBookCatalog/GetBooks", ReplyAction="http://tempuri.org/IWsBookCatalog/GetBooksResponse")]
        System.Data.DataSet GetBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsBookCatalog/GetBookDetails", ReplyAction="http://tempuri.org/IWsBookCatalog/GetBookDetailsResponse")]
        System.Data.DataSet GetBookDetails(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsBookCatalog/CreateOrders", ReplyAction="http://tempuri.org/IWsBookCatalog/CreateOrdersResponse")]
        int CreateOrders(string customerid, ABCHealth.bbs_svc.Order[] bookOrder);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsBookCatalogChannel : ABCHealth.bbs_svc.IWsBookCatalog, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsBookCatalogClient : System.ServiceModel.ClientBase<ABCHealth.bbs_svc.IWsBookCatalog>, ABCHealth.bbs_svc.IWsBookCatalog {
        
        public WsBookCatalogClient() {
        }
        
        public WsBookCatalogClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsBookCatalogClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsBookCatalogClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsBookCatalogClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetBooks() {
            return base.Channel.GetBooks();
        }
        
        public System.Data.DataSet GetBookDetails(int bookId) {
            return base.Channel.GetBookDetails(bookId);
        }
        
        public int CreateOrders(string customerid, ABCHealth.bbs_svc.Order[] bookOrder) {
            return base.Channel.CreateOrders(customerid, bookOrder);
        }
    }
}
