//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT2605Prac03Client.myproxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/IT2605Prac02")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseStudyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal StudentGPAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseStudy {
            get {
                return this.CourseStudyField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseStudyField, value) != true)) {
                    this.CourseStudyField = value;
                    this.RaisePropertyChanged("CourseStudy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StudentGPA {
            get {
                return this.StudentGPAField;
            }
            set {
                if ((this.StudentGPAField.Equals(value) != true)) {
                    this.StudentGPAField = value;
                    this.RaisePropertyChanged("StudentGPA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentID {
            get {
                return this.StudentIDField;
            }
            set {
                if ((this.StudentIDField.Equals(value) != true)) {
                    this.StudentIDField = value;
                    this.RaisePropertyChanged("StudentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentName {
            get {
                return this.StudentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentNameField, value) != true)) {
                    this.StudentNameField = value;
                    this.RaisePropertyChanged("StudentName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="myproxy.IWsIT2605Pra02")]
    public interface IWsIT2605Pra02 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsIT2605Pra02/HelloWorld", ReplyAction="http://tempuri.org/IWsIT2605Pra02/HelloWorldResponse")]
        string HelloWorld(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsIT2605Pra02/HelloWorld", ReplyAction="http://tempuri.org/IWsIT2605Pra02/HelloWorldResponse")]
        System.Threading.Tasks.Task<string> HelloWorldAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsIT2605Pra02/GetStudent", ReplyAction="http://tempuri.org/IWsIT2605Pra02/GetStudentResponse")]
        IT2605Prac03Client.myproxy.Student GetStudent(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsIT2605Pra02/GetStudent", ReplyAction="http://tempuri.org/IWsIT2605Pra02/GetStudentResponse")]
        System.Threading.Tasks.Task<IT2605Prac03Client.myproxy.Student> GetStudentAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsIT2605Pra02Channel : IT2605Prac03Client.myproxy.IWsIT2605Pra02, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsIT2605Pra02Client : System.ServiceModel.ClientBase<IT2605Prac03Client.myproxy.IWsIT2605Pra02>, IT2605Prac03Client.myproxy.IWsIT2605Pra02 {
        
        public WsIT2605Pra02Client() {
        }
        
        public WsIT2605Pra02Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsIT2605Pra02Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsIT2605Pra02Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsIT2605Pra02Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld(string username) {
            return base.Channel.HelloWorld(username);
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync(string username) {
            return base.Channel.HelloWorldAsync(username);
        }
        
        public IT2605Prac03Client.myproxy.Student GetStudent(int id) {
            return base.Channel.GetStudent(id);
        }
        
        public System.Threading.Tasks.Task<IT2605Prac03Client.myproxy.Student> GetStudentAsync(int id) {
            return base.Channel.GetStudentAsync(id);
        }
    }
}
